name: safenest
description: "SafeNest - Parental Control App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  flutter_secure_storage: any
  flutter_local_notifications: any
  provider: any
  shared_preferences: any
  shimmer_effect: any
  url_launcher: any
  connectivity_plus: any
  device_info_plus: any
  permission_handler: any
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_messaging: any
  firebase_analytics: any
  firebase_crashlytics: any
  google_sign_in: ^6.1.0
  sign_in_with_apple: any
  firebase_database: any
  geolocator: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
