// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiZ_VBa4nFH1rc8inA92Uubd2obqktplA',
    appId: '1:1057482950164:web:be0ff94d4a9ec27038c901',
    messagingSenderId: '1057482950164',
    projectId: 'safenest-2025-app',
    authDomain: 'safenest-2025-app.firebaseapp.com',
    storageBucket: 'safenest-2025-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX736JVAcSx0OkHcFCBGBzHbFrxmujjbs',
    appId: '1:1057482950164:android:deceb935e3416e9038c901',
    messagingSenderId: '1057482950164',
    projectId: 'safenest-2025-app',
    storageBucket: 'safenest-2025-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8JnYivu_40xt6-mmcZ9BFq66USC7LdJs',
    appId: '1:1057482950164:ios:cb331fd82ef56fe838c901',
    messagingSenderId: '1057482950164',
    projectId: 'safenest-2025-app',
    storageBucket: 'safenest-2025-app.firebasestorage.app',
    androidClientId: '1057482950164-9o7nta1ti5beomc1177jvrdg06cr0ibh.apps.googleusercontent.com',
    iosClientId: '1057482950164-47n3v6b337ah24h46sg5v2mss0i90ahu.apps.googleusercontent.com',
    iosBundleId: 'com.example.safenest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8JnYivu_40xt6-mmcZ9BFq66USC7LdJs',
    appId: '1:1057482950164:ios:cb331fd82ef56fe838c901',
    messagingSenderId: '1057482950164',
    projectId: 'safenest-2025-app',
    storageBucket: 'safenest-2025-app.firebasestorage.app',
    androidClientId: '1057482950164-9o7nta1ti5beomc1177jvrdg06cr0ibh.apps.googleusercontent.com',
    iosClientId: '1057482950164-47n3v6b337ah24h46sg5v2mss0i90ahu.apps.googleusercontent.com',
    iosBundleId: 'com.example.safenest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiZ_VBa4nFH1rc8inA92Uubd2obqktplA',
    appId: '1:1057482950164:web:1dbd9b18e975554b38c901',
    messagingSenderId: '1057482950164',
    projectId: 'safenest-2025-app',
    authDomain: 'safenest-2025-app.firebaseapp.com',
    storageBucket: 'safenest-2025-app.firebasestorage.app',
  );

}